### ISSUE TITLE
an exception is being thrown when using a list in a post body

### ISSUE THREAD

**Issue by SPiercer** [Cleveroad/cr_logger#21]
```dart
final response = await client.put(
  '/route',
  body: [
    {'id': id}
  ],
);
```

when i send an array/list in the body it throws an exception where `List<Map<String,dynamic>>` not subtype of `Map<String,dynamic>`
when showing the request in the logs screen

httpclient used is Dio

**Comment by WiRight** [comment]
Hey! Maybe i fixed this in #20 
But is not merged yet...

You can use is like

```yaml
dependency_overrides:
  cr_logger:
    git:
      url: https://github.com/DizoftTeam/cr_logger.git
```

**Comment by guccisekspir** [comment]
Even library updated 2 weeks ago this 2 years issue still remain. I am not sure that there is big amount of work.
